In [31]:
#import libraries pandas and numpy 
import pandas as pd 
import numpy as np

In [32]:
#read the csv file 
dataset = pd.read_csv("Car Ownership.csv")

In [33]:
#the size of the data and the number of columns and rows 
dataset.shape

(500, 8)

In [34]:
#to show us the columns and the rows 
dataset.head(10)

,Occupation,MonthlyIncome,CreditScore,YearsofEmployment,FinanceStatus,FinanceHistory,Car,NumberofChildren
0,Teacher,40000,750.0,10,Good,No issues,Yes,2
1,Engineer,60000,800.0,8,Good,No issues,Yes,1
2,Nurse,25000,650.0,5,Fair,Late payment 2 months ago,No,0
3,Doctor,80000,900.0,12,Excellent,No issues,Yes,3
4,Businessman,100000,700.0,15,Good,Late payment 6 months ago,Yes,2
5,Engineer,50000,750.0,6,Fair,No issues,No,1
6,Teacher,35000,700.0,8,Fair,Late payment 3 months ago,Yes,NaN
7,Nurse,20000,600.0,3,Poor,Late payment 1 month ago,No,NaN
8,Businessman,120000,850.0,20,Excellent,No issues,Yes,NaN
9,Doctor,90000,800.0,10,Good,No issues,Yes,NaN

In [35]:
# to see each columns data type and non-null count 
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Occupation         490 non-null    object
 1   MonthlyIncome      487 non-null    object
 2   CreditScore        460 non-null    float64
 3   YearsofEmployment  457 non-null    object
 4   FinanceStatus      477 non-null    object
 5   FinanceHistory     472 non-null    object
 6   Car                480 non-null    object
 7   NumberofChildren   375 non-null    object
dtypes: float64(1), object(7)
memory usage: 17.6+ KB

Data Cleaning

In [36]:
#to see the null values 
dataset.isna()

,Occupation,MonthlyIncome,CreditScore,YearsofEmployment,FinanceStatus,FinanceHistory,Car,NumberofChildren
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False

In [37]:
#if there is a duplicate data 
dataset.duplicated().sum()

73

In [38]:
#remove the duplicate data 
dataset.drop_duplicates(keep ="first", inplace= True)

In [39]:
dataset.duplicated().sum()

0

In [40]:
#to see the size of the data after removing the duplicated data 
dataset.shape

(427, 8)

In [41]:
#to see from each attribute the number of missing data 
dataset.isna().sum()

Occupation            1
MonthlyIncome         4
CreditScore          31
YearsofEmployment    34
FinanceStatus        14
FinanceHistory       19
Car                  11
NumberofChildren     79
dtype: int64

In [42]:
#to see if there is a problem in this attribute 
dataset['Occupation'].unique()

array(['Teacher', 'Engineer', 'Nurse', 'Doctor', 'Businessman', nan,
       'Salesperson', 'Entrepreneur', 'Lawyer', 'Accountant',
       'Software Dev', 'Electrician', 'Architect', 'Marketing Exec',
       'Chef', 'Police Officer', 'Real Estate Ag', 'Pilot',
       'Graphic Design', 'Writer', 'Musician', 'Software Developer',
       'Mechanic', 'Marketing', 'Graphic Designer', 'Financial Advisor',
       'Real Estate Agent', 'Construction Worker', 'Designer',
       'Web Developer', 'Account Manager', 'Financial Analyst',
       'Human Resources', 'Plumber', 'Social Worker', 'Data Scientist',
       'Customer Service', 'Veterinarian', 'Web Designer',
       'Insurance Agent', 'Sales Representative', 'Marketing Manager',
       'Software Engineer', 'Dental Hygienist', 'Retail Manager',
       'Personal Trainer', 'Pharmacist', 'Computer Programmer',
       'Physical Therapist', 'Physician', 'Project Manager',
       'Hairdresser', 'Mechanical Engineer', 'IT Manager',
       'Marketing Specialist', 'Carpenter', 'Optometrist',
       'Graphic Artist', 'Dental Assistant', 'Fashion Designer',
       'Business Owner', 'Barista', 'Physical Education Teacher',
       'Human Resources Manager', 'Photographer', 'Waiter/Waitress',
       'Hair Stylist', 'Psychologist', 'Medical Assistant', 'Bartender',
       'Physician Assistant', 'Customer Service Rep',
       'Elementary School Teacher', 'Librarian', 'Retail Salesperson',
       'Executive Assistant', 'Automotive Mechanic', 'Flight Attendant',
       'Physical Therapist Assistant', 'Financial Manager',
       'Veterinarian Technician', 'Marketing Coordinator', 'Bank Teller',
       'Event Planner', 'Office Manager', 'Business Analyst',
       'Insurance Underwriter', 'Marketing Analyst',
       'IT Support Specialist', 'Data Analyst', 'Mechanical Technician',
       'Sales Manager', 'Account Executive', 'HR Generalist', 'Attorney',
       'HR Specialist', 'Nurse Practitioner', 'Physical Trainer',
       'Interior Designer', 'Computer Technician', 'Dentist',
       'Fitness Instructor', 'Software Architect', 'IT Consultant',
       'Copywriter', 'Electrical Engineer', 'Investment Banker',
       'Registered Nurse', 'Art Director', 'Mechanical Designer',
       'Civil Engineer', 'Social Media Manager', 'Financial Planner',
       'Public Relations', 'HR Manager', 'Management Consultant',
       'Customer Support'], dtype=object)

In [43]:
#I used the mode() to see the most frequent job to fill it in the null values 
Occupation_mode = dataset.Occupation.mode()[0]
print(Occupation_mode)

Chef

In [44]:
#in this line it fill the null values 
dataset.Occupation.fillna(Occupation_mode, inplace=True)

In [45]:
#to see the most frequent monthly income between the employees
MonthlyIncome_mode = dataset.MonthlyIncome.mode()[0]
print(MonthlyIncome_mode)

$4,500

In [46]:
#to fill the missing values 
dataset.MonthlyIncome.fillna(MonthlyIncome_mode, inplace=True)

In [47]:
#to see if there is a problem to clean it 
dataset['MonthlyIncome'].unique()

array(['40000', '60000', '25000', '80000', '100000', '50000', '35000',
       '20000', '120000', '90000', '$4,500 ', '6000', '3000', '4000',
       '8000', '9000', '12000', '5000', '7000', '3500', '2500', '5500',
       '4500', '10000', '2000', '$7,800 ', '$3,200 ', '$6,500 ',
       '$3,000 ', '$3,800 ', '$10,000 ', '$2,500 ', '$5,200 ', '$3,700 ',
       '$8,500 ', '$6,200 ', '$2,800 ', '$9,000 ', '$6,000 ', '$3,500 ',
       '$5,800 ', '$6,800 ', '$2,700 ', '$3,600 ', '$9,200 ', '$3,100 ',
       '$7,000 ', '$4,800 ', '$4,200 ', '$7,500 ', '$5,000 ', '3.2k USD',
       '8.5k USD', '9k', '$4,000 ', '$8,000 ', '$15,000 ', '5k',
       '$9,500 ', '$5,500 ', '$12,000 ', '15k', '$2,000 ', '$1,500 ',
       '$7,200 ', '2.8k', '7.5k', '5000 usd', '2500 usd', '8000 usd',
       '9000 USD', '10000 USD', '3500 USD', '2.5k', '6000 usd',
       '4500 usd', '$2,200 ', '$8 ', '$2,900 ', '$4,100 ', '$8,200 ',
       '$3,900 ', '$4,400 ', '$6,100 ', '$3,400 ', '$8,400 ', '$11,000 ',
       '$4,600 ', '$5,400 ', '11k', '$8,600 ', '3400 usd', '$6,900 ',
       '$4,300 ', '3200 USD', '$', '$10,500 ', '$7 '], dtype=object)

##start cleaning and fixing the problems in the manthly Income attribute ##

In [48]:
dataset['MonthlyIncome'] = dataset['MonthlyIncome'].str.replace("k","000")

In [49]:
dataset['MonthlyIncome'] = dataset['MonthlyIncome'].str.replace("usd","")

In [50]:
dataset['MonthlyIncome'] = dataset['MonthlyIncome'].str.replace("USD","")

In [24]:
dataset['MonthlyIncome'] = dataset['MonthlyIncome'].replace("USD","")

In [53]:
dataset['MonthlyIncome'] = dataset['MonthlyIncome'].replace("$","")

In [54]:
#to see if still there is a problem 
dataset['MonthlyIncome'].unique()

array(['40000', '60000', '25000', '80000', '100000', '50000', '35000',
       '20000', '120000', '90000', '4,500 ', '6000', '3000', '4000',
       '8000', '9000', '12000', '5000', '7000', '3500', '2500', '5500',
       '4500', '10000', '2000', '7,800 ', '3,200 ', '6,500 ', '3,000 ',
       '3,800 ', '10,000 ', '2,500 ', '5,200 ', '3,700 ', '8,500 ',
       '6,200 ', '2,800 ', '9,000 ', '6,000 ', '3,500 ', '5,800 ',
       '6,800 ', '2,700 ', '3,600 ', '9,200 ', '3,100 ', '7,000 ',
       '4,800 ', '4,200 ', '7,500 ', '5,000 ', '3.2000 ', '8.5000 ',
       '4,000 ', '8,000 ', '15,000 ', '9,500 ', '5,500 ', '12,000 ',
       '15000', '2,000 ', '1,500 ', '7,200 ', '2.8000', '7.5000', '5000 ',
       '2500 ', '8000 ', '9000 ', '10000 ', '3500 ', '2.5000', '6000 ',
       '4500 ', '2,200 ', '8 ', '2,900 ', '4,100 ', '8,200 ', '3,900 ',
       '4,400 ', '6,100 ', '3,400 ', '8,400 ', '11,000 ', '4,600 ',
       '5,400 ', '11000', '8,600 ', '3400 ', '6,900 ', '4,300 ', '3200 ',
       '', '10,500 ', '7 '], dtype=object)

In [55]:
#using medain fuction 
CreditScore_median = dataset.CreditScore.median()
print(CreditScore_median)

697.5

In [56]:
#fill the missing values 
dataset.CreditScore.fillna(CreditScore_median, inplace=True)

In [57]:
#change data type 
dataset['CreditScore'] = dataset['CreditScore'].astype('int')

In [58]:
#to see if there is a problem or not 
dataset['CreditScore'].unique()

array([750, 800, 650, 900, 700, 600, 850, 697, 820, 720, 780, 550, 740,
       690, 620, 680, 760, 670, 500, 790, 610, 590, 730, 640, 630, 710,
       660, 840, 890, 770, 830, 560, 810, 570, 689, 755, 765, 631, 643,
       718, 598, 806, 642, 693, 728, 724, 672, 703, 792, 678, 723, 775,
       758, 702, 795, 715, 654, 742, 732, 695, 726, 725, 708, 745, 641])

In [59]:
#to see the most frequent value 
YearsofEmployment_mode = dataset.YearsofEmployment.mode()[0]
print(YearsofEmployment_mode)

4 years

In [60]:
#to fill the missing values in this attrbuite 
dataset.YearsofEmployment.fillna(YearsofEmployment_mode, inplace=True)

In [61]:
#to see if there is a problem to fix it or not 
dataset['YearsofEmployment'].unique()

array(['10', '8', '5', '12', '15', '6', '3', '20', '4 years', '1', '7',
       '4', '2', '3 years', '5 years', '2 years', '7 years', '1 year',
       '8 years', '6 years', '2 y', '3 year', '2 year', '6 year', '7 y',
       '10 years', '12 years', '3 y', '9 years', '11 years', '7 year',
       '8 year', '4 year', '5 year'], dtype=object)

In [62]:
#fixing by replacing 
dataset['YearsofEmployment'] = dataset['YearsofEmployment'].str.replace("ears","")

In [63]:
#to see if there is any problems left 
dataset['YearsofEmployment'].unique()

array(['10', '8', '5', '12', '15', '6', '3', '20', '4 y', '1', '7', '4',
       '2', '3 y', '5 y', '2 y', '7 y', '1 year', '8 y', '6 y', '3 year',
       '2 year', '6 year', '10 y', '12 y', '9 y', '11 y', '7 year',
       '8 year', '4 year', '5 year'], dtype=object)

In [64]:
dataset['YearsofEmployment'] = dataset['YearsofEmployment'].str.replace("ear","")

In [65]:
dataset['YearsofEmployment'].unique()

array(['10', '8', '5', '12', '15', '6', '3', '20', '4 y', '1', '7', '4',
       '2', '3 y', '5 y', '2 y', '7 y', '1 y', '8 y', '6 y', '10 y',
       '12 y', '9 y', '11 y'], dtype=object)

In [66]:
dataset['YearsofEmployment'] = dataset['YearsofEmployment'].str.replace("y","")

In [67]:
#check one last time 
dataset['YearsofEmployment'].unique()

array(['10', '8', '5', '12', '15', '6', '3', '20', '4 ', '1', '7', '4',
       '2', '3 ', '5 ', '2 ', '7 ', '1 ', '8 ', '6 ', '10 ', '12 ', '9 ',
       '11 '], dtype=object)

In [68]:
#see if there is a missing values 
dataset.isna().sum()

Occupation            0
MonthlyIncome         0
CreditScore           0
YearsofEmployment     0
FinanceStatus        14
FinanceHistory       19
Car                  11
NumberofChildren     79
dtype: int64

In [69]:
# see if there is a problem in this attribute 
dataset['FinanceStatus'].unique()

array(['Good', 'Fair', 'Excellent', 'Poor', nan, 'Stable', 'Unstable',
       'Unknow', 'Unkonw'], dtype=object)

In [70]:
#to calculate i used the mode() function to see the most frequent status 
FinanceStatus_mode = dataset.FinanceStatus.mode()[0]
print(FinanceStatus_mode)

Stable

In [71]:
#to fill the null values with the result of FinanceStatus_mode 
dataset.FinanceStatus.fillna(FinanceStatus_mode, inplace=True)

In [72]:
#to see if the problem fixed 
dataset['FinanceStatus'].unique()

array(['Good', 'Fair', 'Excellent', 'Poor', 'Stable', 'Unstable',
       'Unknow', 'Unkonw'], dtype=object)

In [73]:
#to check on the missing values 
dataset.isna().sum()

Occupation            0
MonthlyIncome         0
CreditScore           0
YearsofEmployment     0
FinanceStatus         0
FinanceHistory       19
Car                  11
NumberofChildren     79
dtype: int64

In [74]:
#to see if there is a problem in this attribute 
dataset['FinanceHistory'].unique()

array(['No issues', 'Late payment 2 months ago',
       'Late payment 6 months ago', 'Late payment 3 months ago',
       'Late payment 1 month ago', nan, 'Excellent', 'Poor', 'Good',
       'Fair', 'No significant issues', 'Missed payments in the past',
       'Late payments', 'Late payment', 'No significant issue',
       'Late payments, collections',
       'Missed payments, collections, charge-offs'], dtype=object)

In [75]:
#start fixing the attribuite by calculating the mode() function 
FinanceHistory_mode = dataset.FinanceHistory.mode()[0]
print(FinanceHistory_mode)

No significant issues

In [76]:
# fill the missing values 
dataset.FinanceHistory.fillna(FinanceHistory_mode, inplace=True)

In [77]:
#see if there is problem 
dataset['Car'].unique()

array(['Yes', 'No', nan], dtype=object)

In [78]:
# using the mode() function to calculate the most frequent Car 
Car_mode = dataset.Car.mode()[0]
print(Car_mode)

Yes

In [79]:
#to fill the missing values 
dataset.Car.fillna(Car_mode, inplace=True)

In [80]:
#to check if still there any missing data or a noisy data left 
dataset['Car'].unique()

array(['Yes', 'No'], dtype=object)

In [81]:
#to chaeck the missing values and the last attribute have 79 missing data or a noisy data 
dataset.isna().sum()

Occupation            0
MonthlyIncome         0
CreditScore           0
YearsofEmployment     0
FinanceStatus         0
FinanceHistory        0
Car                   0
NumberofChildren     79
dtype: int64

In [82]:
#to check if there is problem 
dataset['NumberofChildren'].unique()

array(['2', '1', '0', '3', nan, '4', 'na'], dtype=object)

In [97]:
#using the mode() function 
NumberofChildren_mode = dataset.NumberofChildren.mode()[0]
print(NumberofChildren_mode)

0

In [84]:
#to fill the missing values 
dataset.NumberofChildren.fillna(NumberofChildren_mode, inplace=True)

In [85]:
#to see if there is a problem in this coloumn 
dataset['NumberofChildren'].unique()

array(['2', '1', '0', '3', '4', 'na'], dtype=object)

In [86]:
# replace the na value with the mode value we dicovered above 
dataset['NumberofChildren'] = dataset['NumberofChildren'].str.replace("na","0")

In [87]:
#change the data type of the number of chlidren attribute 
dataset['NumberofChildren'] = dataset['NumberofChildren'].astype('int')

In [88]:
#to see if there is a null data or not 
dataset.isna().sum()

Occupation           0
MonthlyIncome        0
CreditScore          0
YearsofEmployment    0
FinanceStatus        0
FinanceHistory       0
Car                  0
NumberofChildren     0
dtype: int64

Data Discretization

In [89]:
#to show for us the dataset
dataset.head(10)

,Occupation,MonthlyIncome,CreditScore,YearsofEmployment,FinanceStatus,FinanceHistory,Car,NumberofChildren
0,Teacher,40000,750,10,Good,No issues,Yes,2
1,Engineer,60000,800,8,Good,No issues,Yes,1
2,Nurse,25000,650,5,Fair,Late payment 2 months ago,No,0
3,Doctor,80000,900,12,Excellent,No issues,Yes,3
4,Businessman,100000,700,15,Good,Late payment 6 months ago,Yes,2
5,Engineer,50000,750,6,Fair,No issues,No,1
6,Teacher,35000,700,8,Fair,Late payment 3 months ago,Yes,0
7,Nurse,20000,600,3,Poor,Late payment 1 month ago,No,0
8,Businessman,120000,850,20,Excellent,No issues,Yes,0
9,Doctor,90000,800,10,Good,No issues,Yes,0

#Perform bucketing using the pd.cut() function

In [90]:
dataset['status'] = pd.cut(dataset['NumberofChildren'],3,labels=['single', 'married', 'devorcid'])

In [91]:
#to see the result after adding new column 
dataset.head(10)

,Occupation,MonthlyIncome,CreditScore,YearsofEmployment,FinanceStatus,FinanceHistory,Car,NumberofChildren,status
0,Teacher,40000,750,10,Good,No issues,Yes,2,married
1,Engineer,60000,800,8,Good,No issues,Yes,1,single
2,Nurse,25000,650,5,Fair,Late payment 2 months ago,No,0,single
3,Doctor,80000,900,12,Excellent,No issues,Yes,3,devorcid
4,Businessman,100000,700,15,Good,Late payment 6 months ago,Yes,2,married
5,Engineer,50000,750,6,Fair,No issues,No,1,single
6,Teacher,35000,700,8,Fair,Late payment 3 months ago,Yes,0,single
7,Nurse,20000,600,3,Poor,Late payment 1 month ago,No,0,single
8,Businessman,120000,850,20,Excellent,No issues,Yes,0,single
9,Doctor,90000,800,10,Good,No issues,Yes,0,single

Data Agreggation

In [92]:
# doing a data frame for the some of the attributes in the csv file 
# i did a data frame to done data agreggation phase 
data = pd.DataFrame(
[[40000, 60000, 25000, 80000],
[750, 800, 650, 900],
[10, 8, 5, 12],
[2, 1, 0, 3]],
columns=['Monthly_Income','Credit_Score', 'Years_of_Employment','Number_of_Children'])
print(data)

   Monthly_Income  Credit_Score  Years_of_Employment  Number_of_Children
0           40000         60000                25000               80000
1             750           800                  650                 900
2              10             8                    5                  12
3               2             1                    0                   3

In [93]:
# here dependeing on the data frame above i count() them , sum(), max(), min() and so on
#then i wrote the agreggation code line also depending on the data frame i did above
data.count()
data['Monthly_Income'].count()
data.sum()
data.max()
data['Credit_Score'].min()
data['Credit_Score'].max()
data['Years_of_Employment'].mean()
print(data['Number_of_Children'].median())
data.agg(['sum', 'min', 'max','mean','median','count','std'])

# after doing the data agreggation part i used the describe() thing to see it more clear. 
data.describe()

456.0

       Monthly_Income  Credit_Score  Years_of_Employment  Number_of_Children
count         4.00000      4.000000             4.000000            4.000000
mean      10190.50000  15202.250000          6413.750000        20228.750000
std       19876.09488  29867.521071         12394.592487        39849.721232
min           2.00000      1.000000             0.000000            3.000000
25%           8.00000      6.250000             3.750000            9.750000
50%         380.00000    404.000000           327.500000          456.000000
75%       10562.50000  15600.000000          6737.500000        20675.000000
max       40000.00000  60000.000000         25000.000000        80000.000000

Data Reduction

In [98]:
#by use sampling to reduce the size of a dataset
# Define the sampling fraction (0.5 for 50% reduction)
#a value of 0.5 will retain 50% of the rows in the dataset
sample_fraction = 0.5

# Perform random sampling to reduce the dataset size
dataset_reduced = dataset.sample(frac=sample_fraction)

In [99]:
#put the result of the reduction in a new csv file 
dataset_reduced.to_csv('reduced_data.csv', index=False)

In [100]:
#see the size of the csv file after doing the reduction 
dataset_reduced.shape

(214, 9)

##The End##